### ISSUE TITLE
How to setup the point of synchronization between consumers and producer?

### ISSUE THREAD

**Issue by navono** [mustafaturan/bus#3]
I see this in example code:
```
// give some time to process events for async consumers
time.Sleep(time.Millisecond * 25)
```
This approach can not be use in production, Is there a more formal way to setup producer and consumers join point?

If there is one consumer, within `Event.Data` can use `channel` or something to synchronize, buf if with multiple consumers, this approach is not feasible.

Any suggestion?

**Comment by navono** [comment]
I think we can use `SyncGroup`.

**Comment by mustafaturan** [comment]
I should have added a [WaitGroup](https://golang.org/pkg/sync/#WaitGroup) example to the example code. I will add a task myself to do it. Thanks for your raising the issue.

**Comment by mustafaturan** [comment]
I made the sample changes on the example project, I hope the [changes](https://github.com/mustafaturan/bus-sample-project/commit/ee88953b9f30dccba02814e0d989765ed50c7ce4) helps. Thanks again for raising the issue.

**Comment by navono** [comment]
Thanks for response, it's helpful.
