### ISSUE TITLE
[feature] Topic support multiple handlers

### ISSUE THREAD

**Issue by navono** [mustafaturan/bus#6]
Currently, one topic only support one handler, as code as:
```
handlers map[string]*Handler
```

but in some scenario, some topic need multiple handlers.

**Comment by mustafaturan** [comment]
You can register as many handler as you want: https://godoc.org/github.com/mustafaturan/bus#Bus.RegisterHandler

**Comment by navono** [comment]
Maybe I didn't describe it clearly.

As the [bus-sample-project](https://github.com/mustafaturan/bus-sample-project), if modity `counter.go` file like this:
```
// Start registers the counter handler
func Start(wg *sync.WaitGroup) {
	b := config.Bus
	h := bus.Handler{Handle: count, Matcher: ".*"}
	b.RegisterHandler(worker, &h)
	fmt.Printf("Registered counter handler...\n")
	
	
	h2 := bus.Handler{Handle: count2, Matcher: ".*"}
	b.RegisterHandler(worker, &h2)
	
	wg.Add(1)
	go increment(wg)
}
```

`count` handler will not be called anymore because of 
```
handlers map[string]*Handler
```

is not a list, it will replace with after new one.

**Comment by mustafaturan** [comment]
What do you think not to use the same name for the handlers. Instead of passing the first arg as ‘worker’ to both, you can use any different name. ‘name’ should be unique per handler and it is not a topic name

**Comment by navono** [comment]
Imagine a scenario where an http service receives a user request. After the service receives the request, it needs to send the same request message to a different service  module for processing. At this time, it is different processing for the same topic name, instead of creating two different names.

**Comment by mustafaturan** [comment]
I am not sure if I understand correctly but I think you are trying register the handler dynamically on run time for each http request. If this is correct here is my suggestion:

* Handlers should be registered once the app runs then they should listen for events for performance reasons. 
* If a handler needs to handle http request, the data can be passed with both of the `context` and `event.Data` to distinguish context specific logic. 
* If you need dynamic handlers then the way is to provide a unique naming on handlers (not for the topics). 
* Handler name and topic names are different concepts. Topic names are not coupled to handler names and handlers names are not coupled to topic names.
